# Generated by Django 2.2.5 on 2019-09-30 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tweeted_at', models.DateTimeField(blank=True, null=True)),
                ('python_tip', models.TextField()),
                ('link', models.URLField(max_length=250)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('retweets', models.PositiveIntegerField(blank=True, null=True)),
                ('who_posted', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tips',
            },
        ),
    ]
